export default {
    ADD_EPIC : 'ADD_EPIC',
    EPIC_NAME_CHANGED : 'EPIC_NAME_CHANGED',
    EDIT_EPIC : 'EDIT_EPIC',
    EPIC_SELECTED : 'EPIC_SELECTED',
    SHOW_ALL_STORIES : 'SHOW_ALL_STORIES',

    ADD_STORY : 'ADD_STORY',
    EDIT_STORY : 'EDIT_STORY',
    STORY_SELECTED : 'STORY_SELECTED',
    STORY_NAME_CHANGED : 'STORY_NAME_CHANGED',
    STORY_DESCRIPTION_CHANGED : 'STORY_DESCRIPTION_CHANGED',
    DONE_STORY : 'DONE_STORY',

    MODAL_ACTION_RESULT : 'MODAL_ACTION_RESULT'
};